### ISSUE TITLE
mock server throwing error

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine_compose#10]
This is the error I get when I try to run the server using the readme command: 
```bash
Traceback (most recent call last):
  File "/Users/yo/anaconda3/envs/intermine_compose/bin/connexion", line 10, in <module>
    sys.exit(main())
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/connexion/cli.py", line 201, in run
    **api_extra_args)
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/connexion/apps/flask_app.py", line 55, in add_api
    self.app.register_blueprint(api.blueprint)
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/flask/blueprints.py", line 186, in register
    deferred(state)
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/flask/blueprints.py", line 207, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/flask/blueprints.py", line 79, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/yo/anaconda3/envs/intermine_compose/lib/python3.6/site-packages/flask/app.py", line 1222, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: /v1.getNewMine
```

**Comment by leoank** [comment]
Possibly due to duplicate endpoints. This issue is already reported here #9. Completely fixing the problem requires a rethinking of the merger script. So, for now, resorting to manually updating the openapi.json.

**Comment by yochannah** [comment]
Can confirm, this now works - thanks @leoank  :) :) :)
